Repository ManahilMuhammad/asp-team-20, pull requests merged in 2025-03, with the labels that each got.

#30 [FEATURE] - Welcome & 404 pages
  src/client/public/nutrifit-logo.svg
  src/client/src/App.tsx
  src/client/src/pages/404.tsx
  src/client/src/pages/Home/index.tsx
Labels: enhancement, feature request

#31 [FIX]: incomplete password check
  src/server/controllers/user.controller.js
Labels: bug

#36 [ENHANCEMENT]: !! Userdata organisation in DB
  src/client/package.json
  src/client/src/components/auth/auth-context.ts
  src/client/src/components/ui/avatar.tsx
  src/client/src/pages/Profile/index.tsx
  src/server/controllers/authController.js
  src/server/controllers/userController.js
  src/server/models/index.js
  src/server/models/models/user.js
  src/server/models/models/userBadges.js
  src/server/routes/user.routes.js
Labels: bug, enhancement

#35 [REFACTOR]: !! recipe tables
  documentation/database_tables/recipes.md
  src/server/controllers/recipeController.js
  src/server/models/index.js
  src/server/models/models/recipe.js
  src/server/models/models/recipes.js
  src/server/models/models/savedRecipes.js
  src/server/routes/recipeRoutes.js
  src/server/server.js
Labels: documentation, enhancement

#34 [FEATURE]: Recipe pages
  src/client/package.json
  src/client/src/App.css
  src/client/src/App.tsx
  src/client/src/components/recipe-card.tsx
  src/client/src/components/ui/scroll-area.tsx
  src/client/src/components/ui/separator.tsx
  src/client/src/components/ui/tooltip.tsx
  src/client/src/hooks/use-fetch-api.ts
  src/client/src/index.css
  src/client/src/main.tsx
  src/client/src/pages/Recipes/Create/main.tsx
  src/client/src/pages/Recipes/Saved/main.tsx
  src/client/src/pages/Recipes/SearchRecipes/main.tsx
  src/client/src/pages/Recipes/Suggested/main.tsx
  src/client/src/pages/Recipes/View/main-invalid.tsx
  src/client/src/pages/Recipes/View/main.tsx
  src/client/src/pages/Recipes/main.tsx
  src/client/src/pages/Recipes/types.ts
  src/client/tailwind.config.js
  src/server/controllers/recipeController.js
  src/server/routes/recipeRoutes.js
Labels: enhancement, feature request

#37 [REFACTOR]: registration process
  src/client/package.json
  src/client/public/base-avatars/avatar-1.svg
  src/client/public/base-avatars/avatar-10.svg
  src/client/public/base-avatars/avatar-11.svg
  src/client/public/base-avatars/avatar-12.svg
  src/client/public/base-avatars/avatar-13.svg
  src/client/public/base-avatars/avatar-14.svg
  src/client/public/base-avatars/avatar-2.svg
  src/client/public/base-avatars/avatar-3.svg
  src/client/public/base-avatars/avatar-4.svg
  src/client/public/base-avatars/avatar-5.svg
  src/client/public/base-avatars/avatar-6.svg
  src/client/public/base-avatars/avatar-7.svg
  src/client/public/base-avatars/avatar-8.svg
  src/client/public/base-avatars/avatar-9.svg
  src/client/src/App.tsx
  src/client/src/components/auth/auth-context.ts
  src/client/src/components/auth/auth-provider.tsx
  src/client/src/components/ui/carousel.tsx
  src/client/src/components/ui/sonner.tsx
  src/client/src/lib/utils.ts
  src/client/src/main.tsx
  src/client/src/pages/Auth/register-form.tsx
  src/client/src/pages/Profile/index.tsx
  src/client/src/pages/Registration/index.tsx
  src/client/src/pages/Registration/pages/1-introduction.tsx
  src/client/src/pages/Registration/pages/2-goal-selection.tsx
  src/client/src/pages/Registration/pages/3-details.tsx
  src/client/src/pages/Registration/pages/4-avatar-selection.tsx
  src/client/src/pages/Registration/pages/5-confirmation.tsx
  src/client/src/pages/Registration/types.ts
  src/server/controllers/userController.js
  src/server/models/models/fitnessMetric.js
  src/server/models/models/user.js
  src/server/routes/userRoutes.js
  src/server/server.js
Labels: enhancement, feature request

#38 [FEATURE]: Profilepage minimum viable product
  src/client/src/lib/utils.ts
  src/client/src/pages/Profile/index.tsx
  src/client/src/pages/Profile/sub-pages/index.tsx
  src/client/src/pages/Profile/sub-pages/settings.tsx
  src/client/src/pages/Profile/types.ts
  src/client/src/pages/Recipes/main.tsx
Labels: enhancement

#42 [DOCUMENTATION]: placeholder data & instructions for recipes model
  .gitattributes
  documentation/database_tables/recipes-placeholder.csv
  documentation/database_tables/recipes.md
Labels: documentation

#41 [FEATURE]: Handling Saved Recipes
  src/client/src/components/recipe-card.tsx
  src/client/src/main.tsx
  src/client/src/pages/Recipes/Saved/main.tsx
  src/client/src/pages/Recipes/View/main.tsx
  src/server/controllers/recipeController.js
  src/server/migrations/20250309204942-create-saved-recipes.js
  src/server/models/models/savedRecipes.js
  src/server/routes/recipeRoutes.js
Labels: enhancement, feature request

#40 Refactor: add missing columns to user table
  src/server/config/config.js
  src/server/controllers/userController.js
  src/server/migrations/20250309025411-add-user-profile-fields.js
  src/server/package-lock.json
  src/server/package.json
Labels: bug
