Repository ManahilMuhammad/asp-team-20, pull requests merged in 2025-02, with the labels that each got.

#14 Infrastructure Refactor
  .gitignore
  documentation/CONTRIBUTING.md
  documentation/setup_guides/client.md
  documentation/setup_guides/server.md
  research/competitor-analysis.md
  research/interviews/user1.mp4
  research/interviews/user2.mp4
  research/interviews/user3.mp4
  research/interviews/user4.mp4
  src/.gitignore
  src/client/.gitkeep
  src/package.json
  src/server/.gitkeep
Labels: documentation

#16 PostGreSQL / Express setup:
  .gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/workspace.xml
  documentation/setup_guides/client/main.md
  documentation/setup_guides/server.md
  documentation/setup_guides/server/authentication.md
  documentation/setup_guides/server/main.md
  src/.gitignore
  src/server/config/config.json
  src/server/controllers/user.controller.js
  src/server/middleware/auth.middelware.js
  src/server/migrations/20250205203457-create-user.js
  src/server/migrations/20250210053910-create-user-recipe.js
  src/server/models/index.js
  src/server/models/user.js
  src/server/node_modules/test
  src/server/package-lock.json
  src/server/package.json
  src/server/routes/user.routes.js
  src/server/server.js
  src/server/utils/generateToken.js
Labels: feature request

#18 Add Recipe model with validations and associations
  src/server/controllers/recipeController.js
  src/server/migrations/20250210053910-create-user-recipe.js
  src/server/migrations/20250214120811-create-recipes-table.js
  src/server/models/recipe.js
  src/server/routes/recipeRoutes.js
  src/server/server.js
Labels: feature request

#21 Feat: Front end project initialisation
  documentation/setup_guides/client/setup-react-vite.md
  src/client/.gitignore
  src/client/components.json
  src/client/eslint.config.js
  src/client/index.html
  src/client/package.json
  src/client/postcss.config.js
  src/client/public/favicon.ico
  src/client/public/vite.svg
  src/client/src/App.css
  src/client/src/App.tsx
  src/client/src/assets/react.svg
  src/client/src/components/auth/auth-context.ts
  src/client/src/components/auth/auth-provider.tsx
  src/client/src/components/theme-toggle.tsx
  src/client/src/components/theme/theme-context.ts
  src/client/src/components/theme/theme-provider.tsx
  src/client/src/components/ui/button.tsx
  src/client/src/components/ui/card.tsx
  src/client/src/components/ui/dropdown-menu.tsx
  src/client/src/components/ui/input.tsx
  src/client/src/components/ui/label.tsx
  src/client/src/hooks/use-auth.ts
  src/client/src/hooks/use-theme.ts
  src/client/src/index.css
  src/client/src/lib/utils.ts
  src/client/src/main.tsx
  src/client/src/pages/Auth/index.tsx
  src/client/src/pages/Auth/login-form.tsx
  src/client/src/pages/Auth/register-form.tsx
  src/client/src/pages/Home/index.tsx
  src/client/src/pages/Profile/index.tsx
  src/client/src/vite-env.d.ts
  src/client/tailwind.config.js
  src/client/tsconfig.app.json
  src/client/tsconfig.json
  src/client/tsconfig.node.json
  src/client/vite.config.ts
Labels: documentation, feature request

#22 [FEATURE]: Backend security improvements
  .gitignore
  documentation/setup_guides/server/main.md
  src/server/.env.template
  src/server/config/config.js
  src/server/config/config.json
  src/server/config/config.template.json
  src/server/middleware/auth.middelware.js
  src/server/models/index.js
  src/server/routes/user.routes.js
  src/server/server.js
  src/server/utils/generateToken.js
Labels: documentation, security

#25 Refactor Auth
  src/client/src/pages/Auth/login-form.tsx
  src/client/src/pages/Auth/register-form.tsx
  src/server/controllers/user.controller.js
Labels: enhancement

#24 [FEATURE]: Project deployment
  .github/workflows/release.yml
  .gitignore
  documentation/setup_guides/build-and-deploy.md
  documentation/setup_guides/server/main.md
  src/client/vite.config.ts
  src/package.json
  src/server/.env.template
  src/server/config/config.js
  src/server/config/config.template.json
  src/server/controllers/fitnessMetricController.js
  src/server/controllers/recipeController.js
  src/server/controllers/user.controller.js
  src/server/esbuild.config.js
  src/server/middleware/auth.middelware.js
  src/server/models/index.js
  src/server/models/models/fitnessMetric.js
  src/server/models/models/recipe.js
  src/server/models/models/user.js
  src/server/package-lock.json
  src/server/package.json
  src/server/server.js
  src/server/utils/generateToken.js
Labels: ci/cd

#27 Add JWT validation endpoint with Sequelize integration
  src/client/src/App.tsx
  src/client/src/components/auth/auth-provider.tsx
  src/client/src/components/protected-route.tsx
  src/server/controllers/authController.js
  src/server/controllers/user.controller.js
  src/server/middleware/auth.middelware.js
  src/server/routes/auth.js
  src/server/server.js
  src/server/utils/validateJWT.js
Labels: enhancement, feature request
